### ISSUE TITLE
OpenFileDialog breaks in net6.0-windows if multiselect=true

### ISSUE THREAD

**Issue by arcutright** [kant2002/WinFormsComInterop#40]
Calling this in the Main() entry point of the program
```csharp
[STAThread]
static void Main(string[] args) {
  System.Runtime.InteropServices.ComWrappers.RegisterForMarshalling(WinFormsComInterop.WinFormsComWrappers.Instance);
  // ...
```

Breaks the multiselect function of the OpenFileDialog, even in DEBUG builds. Using the following sample code from a Form's main thread, the dialog will not let me click 'open'. Removing the WinFormsComInterop call above, it works fine again. If I disable multiselect, it works with WinFormsComInterop. Even when only selecting 1 file it breaks the dialog.

```csharp
using var dialog = new System.Windows.Forms.OpenFileDialog() {
    Title = title,
    Filter = filter,
    InitialDirectory = searchDirectory,
    Multiselect = true, // doesn't work with WinFormsComWrappers
    DereferenceLinks = true,
};
if (dialog.ShowDialog() == System.Windows.Forms.DialogResult.OK) {
    return dialog.FileNames;
}
```

using a net6-windows target:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
  <TargetFrameworks>net6.0-windows</TargetFrameworks>
  <OutputType>Exe</OutputType>
  <LangVersion>10.0</LangVersion>

  <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  <UseWindowsForms>true</UseWindowsForms>
  <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  <ApplicationHighDpiMode>true</ApplicationHighDpiMode>

  <PlatformTarget>x64</PlatformTarget>
  <Platforms>AnyCPU;x64;x86</Platforms>
  <Configurations>Debug;Release</Configurations>
  <Prefer32Bit>false</Prefer32Bit>
<!-- ... -->
```

**Comment by arcutright** [comment]
This also completely breaks the OpenFileDialog from PresentationFramework

```csharp
var dialog = new Microsoft.Win32.OpenFileDialog() {
  Title = title,
  Filter = filter,
  InitialDirectory = searchDirectory,
};
if (dialog.ShowDialog() == true) {
  return dialog.FileNames;
}
```

```
System.InvalidCastException: Unable to cast object of type 'WinFormsComInterop.IFileOpenDialogWrapper' to type 'MS.Internal.AppModel.IFileDialog'.
   at Microsoft.Win32.OpenFileDialog.CreateVistaDialog()
   at Microsoft.Win32.FileDialog.RunVistaDialog(IntPtr hwndOwner)
   at Microsoft.Win32.FileDialog.RunDialog(IntPtr hwndOwner)
   at Microsoft.Win32.CommonDialog.ShowDialog()
```

**Comment by kant2002** [comment]
Hi, thanks for reporting. First one is what I would be looking into, it seems legit. Second issue, is somewhat problematic because WPF is far from perfect and I think I cannot do anything with WPF for now. See https://github.com/dotnet/wpf/issues/5305#issuecomment-1148621250 for current state of WPF + NativeAOT.

**Comment by kant2002** [comment]
@arcutright what version of WinFormsComInterop you have in your project? I expect Multiselect to work in 0.2.9

**Comment by arcutright** [comment]
I'm using 0.2.9. Here's the full list of references in the project.

```xml
<PackageReference Include="WinFormsComInterop" Version="0.2.9" />
<PackageReference Include="Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers" Version="0.4.336902">
  <PrivateAssets>all</PrivateAssets>
</PackageReference>
<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
<PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
<PackageReference Include="System.Windows.Forms.DataVisualization" Version="1.0.0-prerelease.20110.1" />
<PackageReference Include="System.Data.SqlClient" Version="4.8.3" />
<COMReference Include="Shell32">
  <Guid>{50A7E9B0-70EF-11D1-B75A-00A0C90564FE}</Guid>
  <VersionMajor>1</VersionMajor>
  <VersionMinor>0</VersionMinor>
  <Lcid>0</Lcid>
  <WrapperTool>tlbimp</WrapperTool>
  <Isolated>False</Isolated>
  <EmbedInteropTypes>True</EmbedInteropTypes>
</COMReference>
```

**Comment by arcutright** [comment]
Here's a demonstration: 
![img](https://puu.sh/JjytZ/2f992117d2.gif)

**Comment by kant2002** [comment]
I still cannot repro on my end. Can you try to to run sample from here https://github.com/kant2002/WinFormsComInterop/tree/main/samples/TrimmingSample ?

**Comment by arcutright** [comment]
I could reproduce it with your sample against 0.2.9, however, it works correctly in 0.3.0.

**Comment by kant2002** [comment]
Can you update your app to 0.3.0 and let me know if update solved your issue?

**Comment by arcutright** [comment]
It did, yes.

**Comment by kant2002** [comment]
Great!
